spring:
  application:
    name: oompa-data-article
  profiles:
    default: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
server:
  port: 8081


